{% set name = "stoken" %}
{% set version = "0.93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cernekee/stoken/archive/v{{ version }}.tar.gz
  sha256: 102e2d112b275efcdc20ef438670e4f24f08870b9072a81fda316efcc38aef9c

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - autoconf
    - automake
    - pkg-config
    - make
  host:
    - nettle
    - gtk3
    - libxml2
    - gmp
    - glib
    - cairo
  run:
    - nettle
    - gtk3
    - libxml2
    - glib
    - cairo

test:
  commands:
    - ${PREFIX}/bin/stoken --version

about:
  home: http://stoken.sf.net
  dev_url: https://github.com/cernekee/stoken
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING.LIB
  summary: RSA SecurID-compatible software token for Linux/UNIX systems
  description: |
    stoken is a tokencode generator compatible with RSA SecurID 128-bit (AES)
    tokens.  The project includes several components:

    * A simple command line interface (CLI) used to manage and manipulate tokens
    * A GTK+ GUI with cut&amp;paste functionality
    * A shared library allowing other software to generate tokencodes on demand

extra:
  recipe-maintainers:
    - stuarteberg
